
spring:
  application:
    name: spring-cloud-feign-consumer

server:
  port: 10852


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10850/eureka/
feign:
  hystrix:
    enabled: true

#Ribbon 超时配置
#ribbon:
#  ConnectTimeout: 500

